name: timecounter
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  core_resources:
    git:
      path: core_resources
      ref: null-safety
      url: https://github.com/icarohs7/unox-flutter-resmodules
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  rxdart: ^0.26.0
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
flutter:
  uses-material-design: true
